In [1]:
import pandas as pd

In [11]:
file = "credit_risk_loan_portfolio_dirty_data.xlsx"

loan_application = pd.read_excel(file, sheet_name = "Loan_Applications")
loan_application

,Application_ID,Customer_ID,Application_Date,Branch,Loan_Type,Employment_Type,Annual_Income_INR,Loan_Amount_INR,Credit_Score,Debt_to_Income_Ratio,Interest_Rate_Pct,Tenure_Months,Application_Status
0,APP000001,CUST00670,2025-09-13,Pune,Home,Self-Employed,83700.25,159297.40,581,0.189,15.59,12.0,NaN
1,APP000002,CUST05805,2022-08-27,NAGPUR,Personal,Business Owner,12851.97,175047.23,382,0.326,9.97,120.0,NaN
2,APP000003,CUST04910,2023-06-11,NaN,Home,Business Owner,96910.49,281745.09,501,0.659,13.25,36.0,REJECTED
3,APP000004,CUST03292,2022-09-09,Mumbai,personal,NaN,53383.74,287817.78,842,0.843,8.03,300.0,Approved
4,APP000005,CUST03248,2024-02-08,Mumbai,Auto,NaN,31950.70,128290.41,477,0.254,15.6,300.0,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,APP009996,CUST03534,2025-10-15,NaN,Personal,salaried,43925.59,98047.37,494,0.7,15.77,60.0,Rejected
9996,APP009997,CUST07476,2025-03-11,Aurangabad,Home,NaN,69794.54,116593.47,492,NaN,NaN,120.0,REJECTED
9997,APP009998,CUST02649,2023-08-05,Mumbai,Auto,salaried,42844.10,171748.48,483,0.575,12.79,300.0,Approved
9998,APP009999,CUST04242,2022-01-28,Pune,Personal,Self employed,39376.47,66469.55,829,0.226,1,12.0,Approved
9999,APP010000,CUST04615,2025-02-04,NaN,Education,Unemployed,153185.40,130875.36,627,0.111,9.55,48.0,Approved

In [18]:
# Identifying NULL values

loan_application.isnull().sum()

Application_ID             0
Customer_ID                0
Application_Date           0
Branch                  2612
Loan_Type               1140
Employment_Type         1782
Annual_Income_INR        250
Loan_Amount_INR            0
Credit_Score             452
Debt_to_Income_Ratio     295
Interest_Rate_Pct        198
Tenure_Months            254
Application_Status       782
dtype: int64

In [24]:
# Handling NULL Values

loan_application['Branch'] = loan_application['Branch'].fillna(loan_application['Branch'].mode()[0])

loan_application['Loan_Type'] = loan_application['Loan_Type'].fillna(loan_application['Loan_Type'].mode()[0])

loan_application['Employment_Type'] = loan_application['Employment_Type'].fillna(loan_application['Employment_Type'].mode()[0])

loan_application['Annual_Income_INR'] = loan_application['Annual_Income_INR'].fillna(loan_application['Annual_Income_INR'].median())

loan_application['Credit_Score'] = pd.to_numeric(loan_application['Credit_Score'], errors = 'coerce')
loan_application['Credit_Score'] = loan_application['Credit_Score'].fillna(loan_application['Credit_Score'].median())

loan_application['Debt_to_Income_Ratio'] = pd.to_numeric(loan_application['Debt_to_Income_Ratio'], errors = 'coerce')
loan_application['Debt_to_Income_Ratio'] = loan_application['Debt_to_Income_Ratio'].fillna(loan_application['Debt_to_Income_Ratio'].median())

loan_application['Interest_Rate_Pct'] = pd.to_numeric(loan_application['Interest_Rate_Pct'], errors = 'coerce')
loan_application['Interest_Rate_Pct'] = loan_application['Interest_Rate_Pct'].fillna(loan_application['Interest_Rate_Pct'].median())

loan_application['Tenure_Months'] = loan_application['Tenure_Months'].fillna(loan_application['Tenure_Months'].median())

loan_application['Application_Status'] = loan_application['Application_Status'].fillna(loan_application['Application_Status'].mode()[0])

loan_application

,Application_ID,Customer_ID,Application_Date,Branch,Loan_Type,Employment_Type,Annual_Income_INR,Loan_Amount_INR,Credit_Score,Debt_to_Income_Ratio,Interest_Rate_Pct,Tenure_Months,Application_Status
0,APP000001,CUST00670,2025-09-13,Pune,Home,Self-Employed,83700.25,159297.40,581.0,0.189,15.59,12.0,Approved
1,APP000002,CUST05805,2022-08-27,NAGPUR,Personal,Business Owner,12851.97,175047.23,382.0,0.326,9.97,120.0,Approved
2,APP000003,CUST04910,2023-06-11,Mumbai,Home,Business Owner,96910.49,281745.09,501.0,0.659,13.25,36.0,REJECTED
3,APP000004,CUST03292,2022-09-09,Mumbai,personal,Self-Employed,53383.74,287817.78,842.0,0.843,8.03,300.0,Approved
4,APP000005,CUST03248,2024-02-08,Mumbai,Auto,Self-Employed,31950.70,128290.41,477.0,0.254,15.60,300.0,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,APP009996,CUST03534,2025-10-15,Mumbai,Personal,salaried,43925.59,98047.37,494.0,0.700,15.77,60.0,Rejected
9996,APP009997,CUST07476,2025-03-11,Aurangabad,Home,Self-Employed,69794.54,116593.47,492.0,0.315,12.49,120.0,REJECTED
9997,APP009998,CUST02649,2023-08-05,Mumbai,Auto,salaried,42844.10,171748.48,483.0,0.575,12.79,300.0,Approved
9998,APP009999,CUST04242,2022-01-28,Pune,Personal,Self employed,39376.47,66469.55,829.0,0.226,1.00,12.0,Approved
9999,APP010000,CUST04615,2025-02-04,Mumbai,Education,Unemployed,153185.40,130875.36,627.0,0.111,9.55,48.0,Approved

In [32]:
# Droping Duplicates

loan_application.drop_duplicates(inplace = True)
loan_application

,Application_ID,Customer_ID,Application_Date,Branch,Loan_Type,Employment_Type,Annual_Income_INR,Loan_Amount_INR,Credit_Score,Debt_to_Income_Ratio,Interest_Rate_Pct,Tenure_Months,Application_Status
0,APP000001,CUST00670,2025-09-13,Pune,Home,Self-Employed,83700.25,159297.40,581.0,0.189,15.59,12.0,Approved
1,APP000002,CUST05805,2022-08-27,NAGPUR,Personal,Business Owner,12851.97,175047.23,382.0,0.326,9.97,120.0,Approved
2,APP000003,CUST04910,2023-06-11,Mumbai,Home,Business Owner,96910.49,281745.09,501.0,0.659,13.25,36.0,REJECTED
3,APP000004,CUST03292,2022-09-09,Mumbai,personal,Self-Employed,53383.74,287817.78,842.0,0.843,8.03,300.0,Approved
4,APP000005,CUST03248,2024-02-08,Mumbai,Auto,Self-Employed,31950.70,128290.41,477.0,0.254,15.60,300.0,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,APP009996,CUST03534,2025-10-15,Mumbai,Personal,salaried,43925.59,98047.37,494.0,0.700,15.77,60.0,Rejected
9996,APP009997,CUST07476,2025-03-11,Aurangabad,Home,Self-Employed,69794.54,116593.47,492.0,0.315,12.49,120.0,REJECTED
9997,APP009998,CUST02649,2023-08-05,Mumbai,Auto,salaried,42844.10,171748.48,483.0,0.575,12.79,300.0,Approved
9998,APP009999,CUST04242,2022-01-28,Pune,Personal,Self employed,39376.47,66469.55,829.0,0.226,1.00,12.0,Approved
9999,APP010000,CUST04615,2025-02-04,Mumbai,Education,Unemployed,153185.40,130875.36,627.0,0.111,9.55,48.0,Approved

In [33]:
loan_application.duplicated().sum()

np.int64(0)

In [103]:
# Handling Inconsistent Data

loan_application['Branch'] = loan_application['Branch'].replace({
    'Aurangabad': 'Aurangabad',
    'Mumbai': 'Mumbai',
    'NAGPUR': 'Nagpur',
    'Nashik': 'Nashik',
    'Pune': 'Pune'
})

loan_application['Loan_Type'] = loan_application['Loan_Type'].replace({
    'Auto': 'Auto',
    'Auto Loan': 'Auto Loan',
    'Business': 'Business',
    'Education': 'Education',
    'HOME': 'Home',
    'personal': 'Personal'
})

loan_application['Employment_Type'] = loan_application['Employment_Type'].replace({
    'Business Owner': 'Business Owner',
    'salaried': 'Salaried',
    'Self-employed': 'Self-Employed',
    'Unemployed': 'Unemployed'
})

loan_application['Application_Status'] = loan_application['Application_Status'].replace({
    'Approved': 'Approved',
    'In Process': 'In Process',
    'Pending': 'Pending',
    'REJECTED': 'Rejected'
})

loan_application

,Application_ID,Customer_ID,Application_Date,Branch,Loan_Type,Employment_Type,Annual_Income_INR,Loan_Amount_INR,Credit_Score,Debt_to_Income_Ratio,Interest_Rate_Pct,Tenure_Months,Application_Status
0,APP000001,CUST00670,2025-09-13,Pune,Home,Self-Employed,83700.25,159297.40,581.0,0.189,15.59,12.0,Approved
1,APP000002,CUST05805,2022-08-27,Nagpur,Personal,Business Owner,12851.97,175047.23,382.0,0.326,9.97,120.0,Approved
2,APP000003,CUST04910,2023-06-11,Mumbai,Home,Business Owner,96910.49,281745.09,501.0,0.659,13.25,36.0,Rejected
3,APP000004,CUST03292,2022-09-09,Mumbai,personal,Self-Employed,53383.74,287817.78,842.0,0.843,8.03,300.0,Approved
4,APP000005,CUST03248,2024-02-08,Mumbai,Auto,Self-Employed,31950.70,128290.41,477.0,0.254,15.60,300.0,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,APP009996,CUST03534,2025-10-15,Mumbai,Personal,Salaried,43925.59,98047.37,494.0,0.700,15.77,60.0,Rejected
9996,APP009997,CUST07476,2025-03-11,Aurangabad,Home,Self-Employed,69794.54,116593.47,492.0,0.315,12.49,120.0,Rejected
9997,APP009998,CUST02649,2023-08-05,Mumbai,Auto,Salaried,42844.10,171748.48,483.0,0.575,12.79,300.0,Approved
9998,APP009999,CUST04242,2022-01-28,Pune,Personal,Self employed,39376.47,66469.55,829.0,0.226,1.00,12.0,Approved
9999,APP010000,CUST04615,2025-02-04,Mumbai,Education,Unemployed,153185.40,130875.36,627.0,0.111,9.55,48.0,Approved

In [87]:
loan_application['Application_Date'] = pd.to_datetime(loan_application['Application_Date'])
loan_application

,Application_ID,Customer_ID,Application_Date,Branch,Loan_Type,Employment_Type,Annual_Income_INR,Loan_Amount_INR,Credit_Score,Debt_to_Income_Ratio,Interest_Rate_Pct,Tenure_Months,Application_Status
0,APP000001,CUST00670,2025-09-13,Pune,Home,Self-Employed,83700.25,159297.40,581.0,0.189,15.59,12.0,Approved
1,APP000002,CUST05805,2022-08-27,Nagpur,Personal,Business Owner,12851.97,175047.23,382.0,0.326,9.97,120.0,Approved
2,APP000003,CUST04910,2023-06-11,Mumbai,Home,Business Owner,96910.49,281745.09,501.0,0.659,13.25,36.0,Rejected
3,APP000004,CUST03292,2022-09-09,Mumbai,personal,Self-Employed,53383.74,287817.78,842.0,0.843,8.03,300.0,Approved
4,APP000005,CUST03248,2024-02-08,Mumbai,Auto,Self-Employed,31950.70,128290.41,477.0,0.254,15.60,300.0,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,APP009996,CUST03534,2025-10-15,Mumbai,Personal,Salaried,43925.59,98047.37,494.0,0.700,15.77,60.0,Rejected
9996,APP009997,CUST07476,2025-03-11,Aurangabad,Home,Self-Employed,69794.54,116593.47,492.0,0.315,12.49,120.0,Rejected
9997,APP009998,CUST02649,2023-08-05,Mumbai,Auto,Salaried,42844.10,171748.48,483.0,0.575,12.79,300.0,Approved
9998,APP009999,CUST04242,2022-01-28,Pune,Personal,Self employed,39376.47,66469.55,829.0,0.226,1.00,12.0,Approved
9999,APP010000,CUST04615,2025-02-04,Mumbai,Education,Unemployed,153185.40,130875.36,627.0,0.111,9.55,48.0,Approved

In [88]:
loan_repayment = pd.read_excel(file, sheet_name = 'Loan_Repayments')
loan_repayment

,Repayment_ID,Application_ID,Due_Date,Payment_Date,Amount_Due_INR,Amount_Paid_INR,Days_Past_Due,Payment_Status
0,PAY000001,APP002268,2023-07-26,2023-08-25,10684.37,10659.35,30,NaN
1,PAY000002,APP002329,2024-04-16,2024-06-15,4553.61,3500.67,60,NaN
2,PAY000003,APP004866,2022-05-28,2022-07-27,14702.35,12939.34,60,Paid
3,PAY000004,APP006620,2022-08-10,NaT,25760.97,18843.91,7,Paid
4,PAY000005,APP002608,2024-09-07,NaT,13496.15,8796.13,NaN,Paid
...,...,...,...,...,...,...,...,...
9995,PAY009996,APP000075,2026-01-25,2026-02-24,11919.93,13077.45,30,NaN
9996,PAY009997,APP008482,2023-06-25,2023-07-25,7793.81,6371.72,30,Paid
9997,PAY009998,APP008181,2023-03-26,2023-04-25,11380.25,8935.11,30,Paid
9998,PAY009999,APP006172,2025-03-23,2025-03-24,8473.94,5450.65,1,NaN
9999,PAY010000,APP009740,2023-03-05,2023-03-06,21218.26,22140.07,1,Paid

In [89]:
# Identifying NULL Values

loan_repayment.isnull().sum()

Repayment_ID          0
Application_ID        0
Due_Date              0
Payment_Date       2652
Amount_Due_INR        0
Amount_Paid_INR     244
Days_Past_Due      1125
Payment_Status      696
dtype: int64

In [90]:
# Handling NULL Values

loan_repayment['Amount_Paid_INR'] = pd.to_numeric(loan_repayment['Amount_Paid_INR'], errors = 'coerce')
loan_repayment['Amount_Paid_INR'] = loan_repayment['Amount_Paid_INR'].fillna(loan_repayment['Amount_Paid_INR'].median())

loan_repayment['Days_Past_Due'] = pd.to_numeric(loan_repayment['Days_Past_Due'], errors = 'coerce')
loan_repayment['Days_Past_Due'] = loan_repayment['Days_Past_Due'].fillna(loan_repayment['Days_Past_Due'].median())

loan_repayment['Payment_Status'] = loan_repayment['Payment_Status'].fillna(loan_repayment['Payment_Status'].mode()[0])

loan_repayment

,Repayment_ID,Application_ID,Due_Date,Payment_Date,Amount_Due_INR,Amount_Paid_INR,Days_Past_Due,Payment_Status
0,PAY000001,APP002268,2023-07-26,2023-08-25,10684.37,10659.35,30.0,Paid
1,PAY000002,APP002329,2024-04-16,2024-06-15,4553.61,3500.67,60.0,Paid
2,PAY000003,APP004866,2022-05-28,2022-07-27,14702.35,12939.34,60.0,Paid
3,PAY000004,APP006620,2022-08-10,NaT,25760.97,18843.91,7.0,Paid
4,PAY000005,APP002608,2024-09-07,NaT,13496.15,8796.13,3.0,Paid
...,...,...,...,...,...,...,...,...
9995,PAY009996,APP000075,2026-01-25,2026-02-24,11919.93,13077.45,30.0,Paid
9996,PAY009997,APP008482,2023-06-25,2023-07-25,7793.81,6371.72,30.0,Paid
9997,PAY009998,APP008181,2023-03-26,2023-04-25,11380.25,8935.11,30.0,Paid
9998,PAY009999,APP006172,2025-03-23,2025-03-24,8473.94,5450.65,1.0,Paid
9999,PAY010000,APP009740,2023-03-05,2023-03-06,21218.26,22140.07,1.0,Paid

In [91]:
# Identifying Duplicates 

loan_repayment.duplicated().sum()

np.int64(100)

In [92]:
# Droping Duplicates

loan_repayment.drop_duplicates(inplace = True)
loan_repayment

,Repayment_ID,Application_ID,Due_Date,Payment_Date,Amount_Due_INR,Amount_Paid_INR,Days_Past_Due,Payment_Status
0,PAY000001,APP002268,2023-07-26,2023-08-25,10684.37,10659.35,30.0,Paid
1,PAY000002,APP002329,2024-04-16,2024-06-15,4553.61,3500.67,60.0,Paid
2,PAY000003,APP004866,2022-05-28,2022-07-27,14702.35,12939.34,60.0,Paid
3,PAY000004,APP006620,2022-08-10,NaT,25760.97,18843.91,7.0,Paid
4,PAY000005,APP002608,2024-09-07,NaT,13496.15,8796.13,3.0,Paid
...,...,...,...,...,...,...,...,...
9995,PAY009996,APP000075,2026-01-25,2026-02-24,11919.93,13077.45,30.0,Paid
9996,PAY009997,APP008482,2023-06-25,2023-07-25,7793.81,6371.72,30.0,Paid
9997,PAY009998,APP008181,2023-03-26,2023-04-25,11380.25,8935.11,30.0,Paid
9998,PAY009999,APP006172,2025-03-23,2025-03-24,8473.94,5450.65,1.0,Paid
9999,PAY010000,APP009740,2023-03-05,2023-03-06,21218.26,22140.07,1.0,Paid

In [93]:
loan_repayment.duplicated().sum()

np.int64(0)

In [94]:
# Handling Inconsistent Data

loan_repayment['Payment_Status'] = loan_repayment['Payment_Status'].replace({
    'Late': 'Late',
    'Missed': 'Missed',
    'OVERDUE': 'Overdue',
    'Paid': 'Paid',
    'Partial': 'Partial'
})

loan_repayment

,Repayment_ID,Application_ID,Due_Date,Payment_Date,Amount_Due_INR,Amount_Paid_INR,Days_Past_Due,Payment_Status
0,PAY000001,APP002268,2023-07-26,2023-08-25,10684.37,10659.35,30.0,Paid
1,PAY000002,APP002329,2024-04-16,2024-06-15,4553.61,3500.67,60.0,Paid
2,PAY000003,APP004866,2022-05-28,2022-07-27,14702.35,12939.34,60.0,Paid
3,PAY000004,APP006620,2022-08-10,NaT,25760.97,18843.91,7.0,Paid
4,PAY000005,APP002608,2024-09-07,NaT,13496.15,8796.13,3.0,Paid
...,...,...,...,...,...,...,...,...
9995,PAY009996,APP000075,2026-01-25,2026-02-24,11919.93,13077.45,30.0,Paid
9996,PAY009997,APP008482,2023-06-25,2023-07-25,7793.81,6371.72,30.0,Paid
9997,PAY009998,APP008181,2023-03-26,2023-04-25,11380.25,8935.11,30.0,Paid
9998,PAY009999,APP006172,2025-03-23,2025-03-24,8473.94,5450.65,1.0,Paid
9999,PAY010000,APP009740,2023-03-05,2023-03-06,21218.26,22140.07,1.0,Paid

In [95]:
customer_profile = pd.read_excel(file, sheet_name = 'Customer_Profiles')
customer_profile

,Profile_ID,Customer_ID,Age,Gender,City,Residence_Type,Education_Level,Monthly_Income_INR
0,PROF000001,CUST04195,39,MALE,mumbai,Owned,Graduate,47805.64
1,PROF000002,CUST04142,23,Female,Mumbai,Rented,High School,35397.73
2,PROF000003,CUST07346,20,NaN,Pune,Mortgage,High School,62821.35
3,PROF000004,CUST02836,44,NaN,Pune,Rent,Diploma,27970.77
4,PROF000005,CUST05328,19,female,Mumbai,owned,Postgraduate,76737.50
...,...,...,...,...,...,...,...,...
9995,PROF009996,CUST04367,71,female,Aurangabad,owned,Postgraduate,32467.68
9996,PROF009997,CUST05868,68,MALE,Nagpur,Owned,NaN,67146.53
9997,PROF009998,CUST06339,55,MALE,mumbai,Owned,Postgraduate,49671.77
9998,PROF009999,CUST04825,27,Other,Pune,Family,NaN,49288.68
9999,PROF010000,CUST00946,32,female,Aurangabad,Rent,Diploma,45828.87

In [96]:
# Identifying NULL values

customer_profile.isnull().sum()

Profile_ID               0
Customer_ID              0
Age                    199
Gender                1843
City                  2702
Residence_Type        1768
Education_Level       1638
Monthly_Income_INR     297
dtype: int64

In [97]:
# Handling NULL Values

customer_profile['Age'] = pd.to_numeric(customer_profile['Age'], errors = 'coerce')
customer_profile['Age'] = customer_profile['Age'].fillna(customer_profile['Age'].median())

customer_profile['Gender'] = customer_profile['Gender'].fillna(customer_profile['Gender'].mode()[0])

customer_profile['City'] = customer_profile['City'].fillna(customer_profile['City'].mode()[0])

customer_profile['Residence_Type'] = customer_profile['Residence_Type'].fillna(customer_profile['Residence_Type'].mode()[0])

customer_profile['Education_Level'] = customer_profile['Education_Level'].fillna(customer_profile['Education_Level'].mode()[0])

customer_profile['Monthly_Income_INR'] = pd.to_numeric(customer_profile['Monthly_Income_INR'], errors = 'coerce')
customer_profile['Monthly_Income_INR'] = customer_profile['Monthly_Income_INR'].fillna(customer_profile['Monthly_Income_INR'].median())

customer_profile

,Profile_ID,Customer_ID,Age,Gender,City,Residence_Type,Education_Level,Monthly_Income_INR
0,PROF000001,CUST04195,39.0,MALE,mumbai,Owned,Graduate,47805.64
1,PROF000002,CUST04142,23.0,Female,Mumbai,Rented,High School,35397.73
2,PROF000003,CUST07346,20.0,Female,Pune,Mortgage,High School,62821.35
3,PROF000004,CUST02836,44.0,Female,Pune,Rent,Diploma,27970.77
4,PROF000005,CUST05328,19.0,female,Mumbai,owned,Postgraduate,76737.50
...,...,...,...,...,...,...,...,...
9995,PROF009996,CUST04367,71.0,female,Aurangabad,owned,Postgraduate,32467.68
9996,PROF009997,CUST05868,68.0,MALE,Nagpur,Owned,Postgraduate,67146.53
9997,PROF009998,CUST06339,55.0,MALE,mumbai,Owned,Postgraduate,49671.77
9998,PROF009999,CUST04825,27.0,Other,Pune,Family,Postgraduate,49288.68
9999,PROF010000,CUST00946,32.0,female,Aurangabad,Rent,Diploma,45828.87

In [98]:
# Identifying Duplicates

customer_profile.duplicated().sum()

np.int64(100)

In [99]:
# Droping Duplicates

customer_profile.drop_duplicates(inplace = True)
customer_profile

,Profile_ID,Customer_ID,Age,Gender,City,Residence_Type,Education_Level,Monthly_Income_INR
0,PROF000001,CUST04195,39.0,MALE,mumbai,Owned,Graduate,47805.64
1,PROF000002,CUST04142,23.0,Female,Mumbai,Rented,High School,35397.73
2,PROF000003,CUST07346,20.0,Female,Pune,Mortgage,High School,62821.35
3,PROF000004,CUST02836,44.0,Female,Pune,Rent,Diploma,27970.77
4,PROF000005,CUST05328,19.0,female,Mumbai,owned,Postgraduate,76737.50
...,...,...,...,...,...,...,...,...
9995,PROF009996,CUST04367,71.0,female,Aurangabad,owned,Postgraduate,32467.68
9996,PROF009997,CUST05868,68.0,MALE,Nagpur,Owned,Postgraduate,67146.53
9997,PROF009998,CUST06339,55.0,MALE,mumbai,Owned,Postgraduate,49671.77
9998,PROF009999,CUST04825,27.0,Other,Pune,Family,Postgraduate,49288.68
9999,PROF010000,CUST00946,32.0,female,Aurangabad,Rent,Diploma,45828.87

In [100]:
customer_profile.duplicated().sum()

np.int64(0)

In [101]:
# Handling Inconsistent Data

customer_profile['Gender'] = customer_profile['Gender'].replace({
    'female': 'Female',
    'MALE': 'Male',
    'Others': 'Others'
})

customer_profile['City'] = customer_profile['City'].replace({
    'Aurangabad': 'Aurangabad',
    'mumbai': 'Mumbai',
    'NAGPUR': 'Nagpur',
    'Nashik': 'Nashik',
    'Pune': 'Pune'
})

customer_profile['Residence_Type'] = customer_profile['Residence_Type'].replace({
    'Family': 'Family',
    'Mortgage': 'Mortgage',
    'owned': 'Owned',
    'Rent': 'Rent',
    'Rented': 'Rented'
})

customer_profile['Education_Level'] = customer_profile['Education_Level'].replace({
    'Diploma': 'Diploma',
    'graduate': 'Graduate',
    'High School': 'High School',
    'Other': 'Other',
    'Postgraduate': 'Postgraduate'
})

customer_profile

,Profile_ID,Customer_ID,Age,Gender,City,Residence_Type,Education_Level,Monthly_Income_INR
0,PROF000001,CUST04195,39.0,Male,Mumbai,Owned,Graduate,47805.64
1,PROF000002,CUST04142,23.0,Female,Mumbai,Rented,High School,35397.73
2,PROF000003,CUST07346,20.0,Female,Pune,Mortgage,High School,62821.35
3,PROF000004,CUST02836,44.0,Female,Pune,Rent,Diploma,27970.77
4,PROF000005,CUST05328,19.0,Female,Mumbai,Owned,Postgraduate,76737.50
...,...,...,...,...,...,...,...,...
9995,PROF009996,CUST04367,71.0,Female,Aurangabad,Owned,Postgraduate,32467.68
9996,PROF009997,CUST05868,68.0,Male,Nagpur,Owned,Postgraduate,67146.53
9997,PROF009998,CUST06339,55.0,Male,Mumbai,Owned,Postgraduate,49671.77
9998,PROF009999,CUST04825,27.0,Other,Pune,Family,Postgraduate,49288.68
9999,PROF010000,CUST00946,32.0,Female,Aurangabad,Rent,Diploma,45828.87

In [102]:
# Saving files in CSV

loan_application.to_csv('Cleaned Loan Application.csv', index = False)
loan_repayment.to_csv('Cleaned Loan Repayment.csv', index = False)
customer_profile.to_csv('Cleaned Customer Profile.csv', index = False)